#──────────────────────────────────────────────────
#─██████████████─██████████████─████████──████████─
#─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██░░██████████─██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░░░░░░░░░██─██░░██──██░░██─────██░░░░░░██─────
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██─────────██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██████─────────██████████████─████████──████████─
#──────────────────────────────────────────────────

api:
  key: ''

settings:
  api: false
  vpn: true'

clients:
  enabled: true
  sensitive: true
  blocked:
    - 'Vanilla'

ghost-block:
  enabled: true
  mode: 'FOX'
  strict: true
  max-ms: 450

alerts:
  message: '&c&lFOX &8>> &e&o%player% &7is using %check% &8[&7%type%&8] &8(#%colour%&8)'
  click-command: '/teleport %player%'
  clear-violations-delay: 15
  console: true
  log: false
  log-format: ''


messages:
  prefix: '&c&lFOX &8>> &e'
  alerts-on: '&c&lFOX &8>> &eAlerts toggled &dOn'
  alerts-off: '&c&lFOX &8>> &eAlerts toggled &cOff'
  vpn-kick: '&c&lFOX &8>> &cVpns are blacklisted on this server!'
  banning: '&c&lFOX &8>> &eBanning %player%'
  join-message: '&c&lFOX &8>> &7%player% &ejoined with &6%client%'
  client-kick: '&c&lFOX &8>> &cThis client isnt supported!'

bans:
  enabled: true
  timer: false
  time: 3
  first-commands:
    - 'kick %player% &c&lFOX &8>> &cCheating'
    - ''
  timer-commands:
    - ''
    - ''

broadcast:
  enabled: true
  message: '%nl% &c&lFOX &8>> &7%player% &cWas banned for &c&lCheating! %nl%'