#──────────────────────────────────────────────────
#─██████████████─██████████████─████████──████████─
#─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██░░██████████─██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░░░░░░░░░██─██░░██──██░░██─────██░░░░░░██─────
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██─────────██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██████─────────██████████████─████████──████████─
#──────────────────────────────────────────────────

api:
  key: 'foxac_fgc2f8r2czeg'

settings:
  api: false
  vpn: true

clients:
  enabled: true
  sensitive: true
  blocked:
    - 'Vanilla'

ghost-block:
  enabled: true
  mode: 'FOX'
  strict: true
  max-ms: 450

alerts:
  message: '&c&l🦊 &8>> &e&o%player% &7is using %check% &8[&7%type%&8] &8(#%colour%&8)'
  click-command: '/teleport %player%'
  clear-violations-delay: 15
  console: true
  log: false
  log-format: ''

discord:
  enabled: false
  ban-message: false
  name: 'Fox AntiCheat'
  image: 'https://ibb.co/5GcBYB9'
  url: 'https://discordapp.com/api/webhooks/925820999075774515/G0BVuFnckLvEkVA3ymKR13xWm_v_dNWyUzycQn196m7WwBFRda9Lo5kLSJ-DuokhoEva'
  banurl: 'https://discordapp.com/api/webhooks/925820999075774515/G0BVuFnckLvEkVA3ymKR13xWm_v_dNWyUzycQn196m7WwBFRda9Lo5kLSJ-DuokhoEva'

messages:
  prefix: '&c&l🦊 &8>> &e'
  alerts-on: '&c&l🦊 &8>> &eAlerts toggled &dOn'
  alerts-off: '&c&l🦊 &8>> &eAlerts toggled &cOff'
  vpn-kick: '&c&l🦊 &8>> &cVpns are blacklisted on this server!'
  banning: '&c&l🦊 &8>> &eBanning %player%'
  join-message: '&c&l🦊 &8>> &7%player% &ejoined with &6%client%'
  client-kick: '&c&l🦊 &8>> &cThis client isnt supported!'

bans:
  enabled: false
  sus: true
  timer: false
  time: 3
  first-commands:
    - 'kick %player% &c&l🦊 &8>> &cCheating'
    - ''
  timer-commands:
    - ''
    - ''

broadcast:
  enabled: true
  message: '%nl% &c&l🦊 &8>> &7%player% &cWas banned for &c&lCheating! %nl%'