#──────────────────────────────────────────────────
#─██████████████─██████████████─████████──████████─
#─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██░░██████████─██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░░░░░░░░░██─██░░██──██░░██─────██░░░░░░██─────
#─██░░██████████─██░░██──██░░██───████░░░░░░████───
#─██░░██─────────██░░██──██░░██───██░░░░██░░░░██───
#─██░░██─────────██░░██████░░██─████░░██──██░░████─
#─██░░██─────────██░░░░░░░░░░██─██░░░░██──██░░░░██─
#─██████─────────██████████████─████████──████████─
#──────────────────────────────────────────────────

api:
  key: ''

settings:
  api: false
  vpn: true # Credits to funkemunky for his amazing vpn api!

clients:
  enabled: false
  sensitive: true
  blocked:
    - 'Vanilla'

ghost-block:
  enabled: true
  mode: 'FOX2'

alerts:
  message: '&c&lFOX &8>> &c%player% &7is using %check% %type%%dev% &8(%colour%&8)'
  messageverbose: '&c&lFOX VERBOSE &8>> &c%player% &7verbosed %check% %type%%dev%'
  click-command: '/teleport %player%'
  clear-violations-delay: 15
  console: true
  log: false
  log-format: ''

discord:
  enabled: false
  ban-message: false
  name: 'Fox AntiCheat'
  image: 'https://ibb.co/K9MQjPD'
  url: 'https://discordapp.com/api/webhooks/925820999075774515/G0BVuFnckLvEkVA3ymKR13xWm_v_dNWyUzycQn196m7WwBFRda9Lo5kLSJ-DuokhoEva'
  banurl: 'https://discordapp.com/api/webhooks/925820999075774515/G0BVuFnckLvEkVA3ymKR13xWm_v_dNWyUzycQn196m7WwBFRda9Lo5kLSJ-DuokhoEva'

messages:
  prefix: '&c&lFOX &8>> &7'
  alerts-on: '&c&lFOX &8>> &7Alerts toggled &aOn'
  alerts-off: '&c&lFOX &8>> &7Alerts toggled &cOff'
  verbose-on: '&c&lFOX &8>> &7Verbose toggled &aOn'
  verbose-off: '&c&lFOX &8>> &7Verbose toggled &cOff'
  vpn-kick: "&c&lFOX &8| &rAntiVPN Detection.%nl%%nl%&7Your IP has been detected as a VPN/Proxy/Tor [%country%]. %nl%&7Please disconnect from your VPN/Proxy/Tor to continiue playing.%nl%%nl%&8&oIf you believe this is a mistake, contact staff at our discord."
  payload-kick: '&c&lFOX &8>> &cYou were kicked for invalid payload!'
  anticrash-kick: '&c&lFOX &8>> &cYou were kicked for crasher/exploits!'
  antiexploit-alert: '&c&lFOX AntiExploit&8>> &c%player% &7failed &c%check%%dev% &7&l[&d%info%&7&l]'
  banning: '&c&lFOX &8>> &7Banning &c%player%'
  join-message: '&c&lFOX &8>> &7%player% &7joined with &6%client%'
  client-kick: '&c&lFOX &8>> &cThis client isnt supported!'
  vanish-on: '&c&lFOX &8>> &7Vanish toggled &aOn'
  vanish-off: '&c&lFOX &8>> &7Vanish toggled &cOff'
  kb-test: '&c&lFOX &8>> &7You just launched &c%player%'
  scare-cmd: '&c&lFOX &8>> &7You just scared &c%player%'


bans:
  enabled: false
  timer: false
  time: 3
  first-commands:
    - 'kick %player% &c&lFOX &8>> &cCheating'
    - ''
  timer-commands:
    - ''
    - ''

broadcast:
  enabled: true
  message: '%nl%&c&lFOX &8>> &7%player% &cWas punished for &c&lCheating!%nl%'