name: Fox
version: 0.1-ALPHA
main: dev.isnow.fox.FoxPlugin
authors: ["5170"]
description: Fox AntiCheat
api-version: 1.13

commands:
  fox:
    description: Commands for Fox Anticheat.
    usage: /fox
    aliases: [foxac, fac, fag]
    permission: fox.commands
  alerts:
    description: toggle alerts
    usage: /alerts
    aliases:
      - notify
    permission: fox.alerts
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - Geyser-Spigot